// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QptDEdd_CCWDF1FDjSVhNK3jdvckJnk',
    appId: '1:77028012240:web:da8b6eb7685c18565e2ed5',
    messagingSenderId: '77028012240',
    projectId: 'pokelens-66bd0',
    authDomain: 'pokelens-66bd0.firebaseapp.com',
    storageBucket: 'pokelens-66bd0.appspot.com',
    measurementId: 'G-RSGJBMBGBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd48lgQIQwd-UbyrYSnG_z2Bg21zk6BeA',
    appId: '1:77028012240:android:5ea525161b7965d45e2ed5',
    messagingSenderId: '77028012240',
    projectId: 'pokelens-66bd0',
    storageBucket: 'pokelens-66bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8GOCV9pY2ib6m2YyeQu89MukJP2_AuM',
    appId: '1:77028012240:ios:17bb078be16642425e2ed5',
    messagingSenderId: '77028012240',
    projectId: 'pokelens-66bd0',
    storageBucket: 'pokelens-66bd0.appspot.com',
    iosBundleId: 'com.example.testeApi',
  );
}
